### ISSUE TITLE
[FANCY GYM] Air Hockey not available (depends on mushroom-rl, dmc, mujoco)  - Warning

### ISSUE THREAD

**Issue by JuliusJacobitz** [ALRhub/fancy_gym#90]
**Describe the bug**
Following the setup guide in the README.md the some dependencies are missing when running `pip install -e '.[all]'`.
When running code a message shows up `[FANCY GYM] Air Hockey not available (depends on mushroom-rl, dmc, mujoco)`
To rm the message run `pip install -e '.[dmc,mushroom-rl,mujoco]'` which is not stated anywhere in the setup guide.

**To Reproduce**
1. Setup clean env
2. Follow README.md instructions

**Expected behavior**
Do not show the Warning Message

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.8
 - Version : Latest commit `dbd3cae`

**Comment by JuliusJacobitz** [comment]
@Thifhi

**Comment by D-o-d-o-x** [comment]
Fixed with #93.

AirHockey is only avaible, if the optional dependencies mushroom-rl, dmc and mujoco are installed.
These should be installed when installing via ` pip install -e '.[all]'`. This was not the case, since `mushroom-rl` was missing from the pyproject.toml. (We currently maintain both a pyproject.toml as well as a setup.py for backwards compat reasons.)

**Comment by JuliusJacobitz** [comment]
can be closed when #93 is merged.
